# Use the Node.js LTS image as a base
FROM node:lts

# Copy app source
COPY . /src

# Set working directory to /src
WORKDIR /src

# Install app dependencies
RUN npm install

# Expose port to outside world
EXPOSE 3000

ARG SPOTIFY_CLIENT_KEY

ENV SPOTIFY_CLIENT_KEY $SPOTIFY_CLIENT_KEY


# Start command as per the package.json file
CMD ["npm", "start"]